#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LoopMeUnitedSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum LoopMeAdOrientation : NSInteger;
enum LoopMeCreativeType : NSInteger;
@class LoopMeMRAIDExpandProperties;
@class LoopMeVastProperties;
enum LoopMeTrackerName : NSInteger;

SWIFT_CLASS_NAMED("AdConfigurationWrapper")
@interface LoopMeAdConfiguration : NSObject
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull adId;
@property (nonatomic, readonly) BOOL isV360;
@property (nonatomic, readonly) BOOL debug;
@property (nonatomic, readonly) BOOL preload25;
@property (nonatomic) enum LoopMeAdOrientation adOrientation;
@property (nonatomic, readonly) enum LoopMeCreativeType creativeType;
@property (nonatomic, copy) NSString * _Nonnull creativeContent;
@property (nonatomic, readonly) BOOL isPortrait;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull adIdsForMoat;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull adIdsForIAS;
@property (nonatomic, strong) LoopMeMRAIDExpandProperties * _Nullable expandProperties;
@property (nonatomic, strong) LoopMeVastProperties * _Nullable vastProperties;
@property (nonatomic) BOOL allowOrientationChange;
- (BOOL)useTracking:(enum LoopMeTrackerName)trackerNameWrapped SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeAdOrientation, "AdOrientationWrapper", closed) {
  LoopMeAdOrientationUndefined = 0,
  LoopMeAdOrientationPortrait = 1,
  LoopMeAdOrientationLandscape = 2,
};

@class LoopMeViewableImpression;
@class LoopMeLinearTracking;

SWIFT_CLASS_NAMED("AdTrackingLinksWrapper")
@interface LoopMeAdTrackingLinks : NSObject
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull errorTemplates;
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull impression;
@property (nonatomic, readonly, copy) NSString * _Nonnull clickVideo;
@property (nonatomic, readonly, copy) NSString * _Nonnull clickCompanion;
@property (nonatomic, readonly, strong) LoopMeViewableImpression * _Nonnull viewableImpression;
@property (nonatomic, readonly, strong) LoopMeLinearTracking * _Nonnull linear;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("AdVerificationWrapper")
@interface LoopMeAdVerification : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull vendor;
@property (nonatomic, readonly, copy) NSString * _Nonnull jsResource;
@property (nonatomic, readonly, copy) NSString * _Nonnull verificationParameters;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("AssetLinksWrapper")
@interface LoopMeAssetLinks : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull videoURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull vpaidURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull adParameters;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull endCard;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeCreativeType, "CreativeTypWrapper", closed) {
  LoopMeCreativeTypeVpaid = 0,
  LoopMeCreativeTypeVast = 1,
  LoopMeCreativeTypeNormal = 2,
  LoopMeCreativeTypeMraid = 3,
};


SWIFT_CLASS_NAMED("LinearTrackingWrapper")
@interface LoopMeLinearTracking : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class LoopMeServerCommunicator;

SWIFT_PROTOCOL("_TtP15LoopMeUnitedSDK32LoopMeServerCommunicatorDelegate_")
@protocol LoopMeServerCommunicatorDelegate <NSObject>
- (void)serverCommunicator:(LoopMeServerCommunicator * _Nonnull)communicator didReceive:(LoopMeAdConfiguration * _Nonnull)adConfiguration;
- (void)serverCommunicator:(LoopMeServerCommunicator * _Nonnull)communicator didFailWith:(NSError * _Nullable)error;
- (void)serverCommunicatorDidReceiveAd:(LoopMeServerCommunicator * _Nonnull)communicator;
@end


SWIFT_CLASS_NAMED("MRAIDExpandPropertiesWrapper")
@interface LoopMeMRAIDExpandProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) float width;
@property (nonatomic) float height;
@property (nonatomic) BOOL useCustomClose;
@end


SWIFT_CLASS_NAMED("ProgressEventTrackerWrapper")
@interface LoopMeProgressEventTracker : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ProgressEventWrappper")
@interface LoopMeProgressEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ServerCommunicator")
@interface LoopMeServerCommunicator : NSObject
@property (nonatomic, copy) NSString * _Nullable appKey;
- (nonnull instancetype)initWithDelegate:(id <LoopMeServerCommunicatorDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (void)loadWithUrl:(NSURL * _Nonnull)url requestBody:(NSData * _Nullable)requestBody method:(NSString * _Nullable)method;
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeTimeOffsetType, "TimeOffsetType", closed) {
  LoopMeTimeOffsetTypePercent = 0,
  LoopMeTimeOffsetTypeSeconds = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeTrackerName, "TrackerNameWrapper", closed) {
  LoopMeTrackerNameIas = 0,
  LoopMeTrackerNameMoat = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeVASTEventType, "VASTEventType", closed) {
  LoopMeVASTEventTypeImpression = 0,
  LoopMeVASTEventTypeLinearStart = 1,
  LoopMeVASTEventTypeLinearFirstQuartile = 2,
  LoopMeVASTEventTypeLinearMidpoint = 3,
  LoopMeVASTEventTypeLinearThirdQuartile = 4,
  LoopMeVASTEventTypeLinearComplete = 5,
  LoopMeVASTEventTypeLinearClose = 6,
  LoopMeVASTEventTypeLinearPause = 7,
  LoopMeVASTEventTypeLinearResume = 8,
  LoopMeVASTEventTypeLinearExpand = 9,
  LoopMeVASTEventTypeLinearCollapse = 10,
  LoopMeVASTEventTypeLinearSkip = 11,
  LoopMeVASTEventTypeLinearMute = 12,
  LoopMeVASTEventTypeLinearUnmute = 13,
  LoopMeVASTEventTypeLinearProgress = 14,
  LoopMeVASTEventTypeLinearClickTracking = 15,
  LoopMeVASTEventTypeCompanionCreativeView = 16,
  LoopMeVASTEventTypeCompanionClickTracking = 17,
  LoopMeVASTEventTypeViewable = 18,
  LoopMeVASTEventTypeNotViewable = 19,
  LoopMeVASTEventTypeViewUndetermined = 20,
};


SWIFT_CLASS_NAMED("VastEventTrackerWrapper")
@interface LoopMeVASTEventTracker : NSObject
- (nonnull instancetype)initWithTrackingLinks:(LoopMeAdTrackingLinks * _Nonnull)trackingLinks OBJC_DESIGNATED_INITIALIZER;
- (void)trackEvent:(enum LoopMeVASTEventType)event;
- (void)trackErrorCode:(NSInteger)code;
- (void)trackAdVerificationNonExecuted;
- (void)setCurrentTime:(NSTimeInterval)currentTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15LoopMeUnitedSDK14VastProperties")
@interface VastProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSXMLParser;

@interface VastProperties (SWIFT_EXTENSION(LoopMeUnitedSDK)) <NSXMLParserDelegate>
- (void)parser:(NSXMLParser * _Nonnull)parser didStartElement:(NSString * _Nonnull)elementName namespaceURI:(NSString * _Nullable)namespaceURI qualifiedName:(NSString * _Nullable)qName attributes:(NSDictionary<NSString *, NSString *> * _Nonnull)attributeDict;
- (void)parser:(NSXMLParser * _Nonnull)parser didEndElement:(NSString * _Nonnull)elementName namespaceURI:(NSString * _Nullable)namespaceURI qualifiedName:(NSString * _Nullable)qName;
- (void)parser:(NSXMLParser * _Nonnull)parser foundCDATA:(NSData * _Nonnull)CDATABlock;
- (void)parser:(NSXMLParser * _Nonnull)parser foundCharacters:(NSString * _Nonnull)string;
@end

@class LoopMeVastSkipOffset;

SWIFT_CLASS_NAMED("VastPropertiesWrapper")
@interface LoopMeVastProperties : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable adId;
@property (nonatomic, readonly) NSTimeInterval duration;
@property (nonatomic, readonly, strong) LoopMeVastSkipOffset * _Nonnull skipOffset;
@property (nonatomic, readonly, strong) LoopMeAdTrackingLinks * _Nonnull trackingLinks;
@property (nonatomic, readonly, strong) LoopMeAssetLinks * _Nonnull assetLinks;
@property (nonatomic, readonly, copy) NSArray<LoopMeAdVerification *> * _Nonnull adVerifications;
@property (nonatomic, readonly) BOOL isVpaid;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VastSkipOffsetWrapper")
@interface LoopMeVastSkipOffset : NSObject
@property (nonatomic, readonly) double value;
@property (nonatomic, readonly) enum LoopMeTimeOffsetType type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ViewableImpressionWrapper")
@interface LoopMeViewableImpression : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LoopMeUnitedSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum LoopMeAdOrientation : NSInteger;
enum LoopMeCreativeType : NSInteger;
@class LoopMeMRAIDExpandProperties;
@class LoopMeVastProperties;
enum LoopMeTrackerName : NSInteger;

SWIFT_CLASS_NAMED("AdConfigurationWrapper")
@interface LoopMeAdConfiguration : NSObject
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull adId;
@property (nonatomic, readonly) BOOL isV360;
@property (nonatomic, readonly) BOOL debug;
@property (nonatomic, readonly) BOOL preload25;
@property (nonatomic) enum LoopMeAdOrientation adOrientation;
@property (nonatomic, readonly) enum LoopMeCreativeType creativeType;
@property (nonatomic, copy) NSString * _Nonnull creativeContent;
@property (nonatomic, readonly) BOOL isPortrait;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull adIdsForMoat;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull adIdsForIAS;
@property (nonatomic, strong) LoopMeMRAIDExpandProperties * _Nullable expandProperties;
@property (nonatomic, strong) LoopMeVastProperties * _Nullable vastProperties;
@property (nonatomic) BOOL allowOrientationChange;
- (BOOL)useTracking:(enum LoopMeTrackerName)trackerNameWrapped SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeAdOrientation, "AdOrientationWrapper", closed) {
  LoopMeAdOrientationUndefined = 0,
  LoopMeAdOrientationPortrait = 1,
  LoopMeAdOrientationLandscape = 2,
};

@class LoopMeViewableImpression;
@class LoopMeLinearTracking;

SWIFT_CLASS_NAMED("AdTrackingLinksWrapper")
@interface LoopMeAdTrackingLinks : NSObject
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull errorTemplates;
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull impression;
@property (nonatomic, readonly, copy) NSString * _Nonnull clickVideo;
@property (nonatomic, readonly, copy) NSString * _Nonnull clickCompanion;
@property (nonatomic, readonly, strong) LoopMeViewableImpression * _Nonnull viewableImpression;
@property (nonatomic, readonly, strong) LoopMeLinearTracking * _Nonnull linear;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("AdVerificationWrapper")
@interface LoopMeAdVerification : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull vendor;
@property (nonatomic, readonly, copy) NSString * _Nonnull jsResource;
@property (nonatomic, readonly, copy) NSString * _Nonnull verificationParameters;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("AssetLinksWrapper")
@interface LoopMeAssetLinks : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull videoURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull vpaidURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull adParameters;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull endCard;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeCreativeType, "CreativeTypWrapper", closed) {
  LoopMeCreativeTypeVpaid = 0,
  LoopMeCreativeTypeVast = 1,
  LoopMeCreativeTypeNormal = 2,
  LoopMeCreativeTypeMraid = 3,
};


SWIFT_CLASS_NAMED("LinearTrackingWrapper")
@interface LoopMeLinearTracking : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class LoopMeServerCommunicator;

SWIFT_PROTOCOL("_TtP15LoopMeUnitedSDK32LoopMeServerCommunicatorDelegate_")
@protocol LoopMeServerCommunicatorDelegate <NSObject>
- (void)serverCommunicator:(LoopMeServerCommunicator * _Nonnull)communicator didReceive:(LoopMeAdConfiguration * _Nonnull)adConfiguration;
- (void)serverCommunicator:(LoopMeServerCommunicator * _Nonnull)communicator didFailWith:(NSError * _Nullable)error;
- (void)serverCommunicatorDidReceiveAd:(LoopMeServerCommunicator * _Nonnull)communicator;
@end


SWIFT_CLASS_NAMED("MRAIDExpandPropertiesWrapper")
@interface LoopMeMRAIDExpandProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) float width;
@property (nonatomic) float height;
@property (nonatomic) BOOL useCustomClose;
@end


SWIFT_CLASS_NAMED("ProgressEventTrackerWrapper")
@interface LoopMeProgressEventTracker : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ProgressEventWrappper")
@interface LoopMeProgressEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ServerCommunicator")
@interface LoopMeServerCommunicator : NSObject
@property (nonatomic, copy) NSString * _Nullable appKey;
- (nonnull instancetype)initWithDelegate:(id <LoopMeServerCommunicatorDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (void)loadWithUrl:(NSURL * _Nonnull)url requestBody:(NSData * _Nullable)requestBody method:(NSString * _Nullable)method;
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeTimeOffsetType, "TimeOffsetType", closed) {
  LoopMeTimeOffsetTypePercent = 0,
  LoopMeTimeOffsetTypeSeconds = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeTrackerName, "TrackerNameWrapper", closed) {
  LoopMeTrackerNameIas = 0,
  LoopMeTrackerNameMoat = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, LoopMeVASTEventType, "VASTEventType", closed) {
  LoopMeVASTEventTypeImpression = 0,
  LoopMeVASTEventTypeLinearStart = 1,
  LoopMeVASTEventTypeLinearFirstQuartile = 2,
  LoopMeVASTEventTypeLinearMidpoint = 3,
  LoopMeVASTEventTypeLinearThirdQuartile = 4,
  LoopMeVASTEventTypeLinearComplete = 5,
  LoopMeVASTEventTypeLinearClose = 6,
  LoopMeVASTEventTypeLinearPause = 7,
  LoopMeVASTEventTypeLinearResume = 8,
  LoopMeVASTEventTypeLinearExpand = 9,
  LoopMeVASTEventTypeLinearCollapse = 10,
  LoopMeVASTEventTypeLinearSkip = 11,
  LoopMeVASTEventTypeLinearMute = 12,
  LoopMeVASTEventTypeLinearUnmute = 13,
  LoopMeVASTEventTypeLinearProgress = 14,
  LoopMeVASTEventTypeLinearClickTracking = 15,
  LoopMeVASTEventTypeCompanionCreativeView = 16,
  LoopMeVASTEventTypeCompanionClickTracking = 17,
  LoopMeVASTEventTypeViewable = 18,
  LoopMeVASTEventTypeNotViewable = 19,
  LoopMeVASTEventTypeViewUndetermined = 20,
};


SWIFT_CLASS_NAMED("VastEventTrackerWrapper")
@interface LoopMeVASTEventTracker : NSObject
- (nonnull instancetype)initWithTrackingLinks:(LoopMeAdTrackingLinks * _Nonnull)trackingLinks OBJC_DESIGNATED_INITIALIZER;
- (void)trackEvent:(enum LoopMeVASTEventType)event;
- (void)trackErrorCode:(NSInteger)code;
- (void)trackAdVerificationNonExecuted;
- (void)setCurrentTime:(NSTimeInterval)currentTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15LoopMeUnitedSDK14VastProperties")
@interface VastProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSXMLParser;

@interface VastProperties (SWIFT_EXTENSION(LoopMeUnitedSDK)) <NSXMLParserDelegate>
- (void)parser:(NSXMLParser * _Nonnull)parser didStartElement:(NSString * _Nonnull)elementName namespaceURI:(NSString * _Nullable)namespaceURI qualifiedName:(NSString * _Nullable)qName attributes:(NSDictionary<NSString *, NSString *> * _Nonnull)attributeDict;
- (void)parser:(NSXMLParser * _Nonnull)parser didEndElement:(NSString * _Nonnull)elementName namespaceURI:(NSString * _Nullable)namespaceURI qualifiedName:(NSString * _Nullable)qName;
- (void)parser:(NSXMLParser * _Nonnull)parser foundCDATA:(NSData * _Nonnull)CDATABlock;
- (void)parser:(NSXMLParser * _Nonnull)parser foundCharacters:(NSString * _Nonnull)string;
@end

@class LoopMeVastSkipOffset;

SWIFT_CLASS_NAMED("VastPropertiesWrapper")
@interface LoopMeVastProperties : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable adId;
@property (nonatomic, readonly) NSTimeInterval duration;
@property (nonatomic, readonly, strong) LoopMeVastSkipOffset * _Nonnull skipOffset;
@property (nonatomic, readonly, strong) LoopMeAdTrackingLinks * _Nonnull trackingLinks;
@property (nonatomic, readonly, strong) LoopMeAssetLinks * _Nonnull assetLinks;
@property (nonatomic, readonly, copy) NSArray<LoopMeAdVerification *> * _Nonnull adVerifications;
@property (nonatomic, readonly) BOOL isVpaid;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VastSkipOffsetWrapper")
@interface LoopMeVastSkipOffset : NSObject
@property (nonatomic, readonly) double value;
@property (nonatomic, readonly) enum LoopMeTimeOffsetType type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ViewableImpressionWrapper")
@interface LoopMeViewableImpression : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
