# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ISLoopMeAdapter' do


  # Pods for ISLoopMeAdapter
   pod 'IronSourceSDK'
    pod 'LoopMeUnitedSDK'

end
